<<<<<<< HEAD
# Generated by Django 5.1 on 2024-08-20 08:28

=======
# Generated by Django 5.1 on 2024-08-22 07:08

import django.db.models.deletion
from django.conf import settings
>>>>>>> 703df48 (.)
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    initial = True

    dependencies = [
=======
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 703df48 (.)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=30)),
                ('ru', models.JSONField()),
                ('transcription', models.CharField(max_length=30)),
                ('data', models.JSONField()),
=======
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en", models.CharField(max_length=30)),
                ("ru", models.JSONField(default=list, null=True)),
                (
                    "transcription",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("data", models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        related_name="favorites", to="english_words_app.word"
                    ),
                ),
>>>>>>> 703df48 (.)
            ],
        ),
    ]
