# Generated by Django 5.1 on 2024-08-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_words_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='data',
            field=models.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru',
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
