# Generated by Django 5.1 on 2024-08-21 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_words_app', '0002_alter_word_data_alter_word_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(null=True, related_name='favorites', to='english_words_app.word')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
